[package]
name = "sniffy"
version = "0.1.0"
edition = "2024"

[dependencies]
aya-ebpf = "0.1.0"
aya-log-ebpf = "0.1.0"
firewall-001-common = { path = "../firewall-001-common" }
network-types = "0.0.5"

