[package]
name = "xdp-drop-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["dep:aya"]

[dependencies]
aya = { version = "0.13.1", optional = true, features = ["macros"] }

[lib]
path = "src/lib.rs"