[package]
name = "myappvictor-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
myappvictor-common = { path = "../myappvictor-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "myappvictor"
path = "src/main.rs"
